/**
 * @fileoverview PostgreSQL integration example for CollegeDB.
 *
 * Wires `node-postgres` (`pg`) into CollegeDB as the SQL backend and
 * `redis` / `valkey` as the KV mapper. The same pattern works for any
 * Postgres-compatible driver (postgres.js, knex, Neon HTTP fetch client, …)
 * as long as it exposes a `query(sql, bindings)` method that returns
 * `{ rows, rowCount }`.
 *
 * Quick start (using Docker Compose):
 *
 * ```bash
 * docker run -d --name pg-east  -e POSTGRES_PASSWORD=postgres -p 5433:5432 postgres:17
 * docker run -d --name pg-west  -e POSTGRES_PASSWORD=postgres -p 5434:5432 postgres:17
 * docker run -d --name redis    -p 6379:6379 redis:7
 *
 * # Create the shared schema on each shard.
 * psql postgres://postgres:postgres@localhost:5433/postgres -c \
 *   "CREATE TABLE users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE)"
 * psql postgres://postgres:postgres@localhost:5434/postgres -c \
 *   "CREATE TABLE users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE)"
 *
 * bun examples/postgresql-integration.ts
 * ```
 *
 * @author CollegeDB Team
 * @since 1.2.2
 */

import { Pool } from 'pg';
import { createClient as createRedisClient } from 'redis';
import {
	allAllShardsGlobal,
	createPostgreSQLProvider,
	createRedisKVProvider,
	first,
	getShardStats,
	initialize,
	insert,
	listKnownShards,
	run,
	type CollegeDBConfig
} from '../src/index';

async function main() {
	const redisClient = createRedisClient({ url: process.env.REDIS_URL ?? 'redis://localhost:6379' });
	await redisClient.connect();

	// CollegeDB rewrites `?` placeholders to `$1..$n` automatically, so the
	// SQL strings below are portable between Postgres, MySQL, SQLite, and D1.
	const east = new Pool({ connectionString: process.env.PG_EAST_URL ?? 'postgres://postgres:postgres@localhost:5433/postgres' });
	const west = new Pool({ connectionString: process.env.PG_WEST_URL ?? 'postgres://postgres:postgres@localhost:5434/postgres' });

	const config: CollegeDBConfig = {
		kv: createRedisKVProvider(redisClient as any),
		shards: {
			'pg-east': createPostgreSQLProvider(east),
			'pg-west': createPostgreSQLProvider(west)
		},
		strategy: 'hash',
		// PG schemas are managed externally (psql/migrations), so skip the
		// internal auto-migration probe.
		disableAutoMigration: true
	};

	initialize(config);

	// Routed insert: the primary key determines the shard via hashing.
	await run('user-1', 'INSERT INTO users (id, name, email) VALUES (?, ?, ?)', ['user-1', 'Ada Lovelace', 'ada@example.com']);

	// Auto-id insert using PostgreSQL's RETURNING clause. The provider
	// captures the returned id and records the shard mapping so routed reads
	// can find the row again.
	await run(
		'audit-bootstrap',
		`CREATE TABLE IF NOT EXISTS audit_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			actor TEXT NOT NULL,
			action TEXT NOT NULL,
			created_at TIMESTAMPTZ DEFAULT now()
		)`
	);
	const audit = await insert('INSERT INTO audit_log (actor, action) VALUES (?, ?) RETURNING id', ['user-1', 'login']);
	console.log('Audit id from RETURNING:', audit.generatedId);

	// Routed read.
	const user = await first<{ id: string; email: string }>('user-1', 'SELECT id, email FROM users WHERE id = ?', ['user-1']);
	console.log('Routed user lookup:', user);

	// Global fanout — useful for cross-shard search.
	const everyone = await allAllShardsGlobal<{ id: string; name: string }>('SELECT id, name FROM users WHERE name LIKE ?', ['%a%'], {
		sortBy: 'name',
		limit: 25
	});
	console.log('Cross-shard search returned', everyone.results.length, 'rows');

	console.log('Known shards:', await listKnownShards());
	console.log('Stats:', await getShardStats());

	await east.end();
	await west.end();
	await redisClient.quit();
}

main().catch((error) => {
	console.error('PostgreSQL integration example failed:', error);
	process.exit(1);
});
