name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Prettier
        run: bun run prettier:check

  test:
    runs-on: ubuntu-latest
    needs: format
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Run type checking
      run: bunx tsc --noEmit
    - name: Run tests
      run: bun test

  build:
    runs-on: ubuntu-latest
    needs: [test, format]
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Build Project
      run: bun run build
    - name: Generate Documentation
      run: bun run docs:build
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: typedoc-documentation
        path: typedoc/
        retention-days: 30
