name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install --frozen-lockfile
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run tests
      run: bunx vitest --reporter=junit --outputFile=test-report.junit.xml
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tests with coverage
      run: bun run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: earth-app/CollegeDB
        fail_ci_if_error: true
        flags: unittests
        files: |
          coverage/coverage-final.json
          coverage/clover.xml
    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage/
          !coverage/node_modules/
        retention-days: 30
