name: Deploy Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build Documentation
        run: bun run docs:build
      - name: Deploy Documentation
        run: bash typedoc.sh ${GITHUB_SHA::7}

